// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALXhj2m2AyN2nhVQ0Cfm0e6dDp_QXFksw',
    appId: '1:196219608404:web:bd5a1684d06ef17a28bcc1',
    messagingSenderId: '196219608404',
    projectId: 'petmatch-77d5b',
    authDomain: 'petmatch-77d5b.firebaseapp.com',
    storageBucket: 'petmatch-77d5b.firebasestorage.app',
    measurementId: 'G-P6Q46F78HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArrTQBFW8bPY2PMr7ektEYPJN7uZ00KO8',
    appId: '1:196219608404:android:67710417ae2fa66b28bcc1',
    messagingSenderId: '196219608404',
    projectId: 'petmatch-77d5b',
    storageBucket: 'petmatch-77d5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXCZDp3pMPPlsbd16nruUpr3bVyvGB3Ys',
    appId: '1:196219608404:ios:2a7b2655f9f1890828bcc1',
    messagingSenderId: '196219608404',
    projectId: 'petmatch-77d5b',
    storageBucket: 'petmatch-77d5b.firebasestorage.app',
    androidClientId: '196219608404-9pu83jks83ukvmog57e961qb1t59tv41.apps.googleusercontent.com',
    iosClientId: '196219608404-ugvcc0oggjqev1bv1r08uacd3cuto7v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.petmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXCZDp3pMPPlsbd16nruUpr3bVyvGB3Ys',
    appId: '1:196219608404:ios:2a7b2655f9f1890828bcc1',
    messagingSenderId: '196219608404',
    projectId: 'petmatch-77d5b',
    storageBucket: 'petmatch-77d5b.firebasestorage.app',
    androidClientId: '196219608404-9pu83jks83ukvmog57e961qb1t59tv41.apps.googleusercontent.com',
    iosClientId: '196219608404-ugvcc0oggjqev1bv1r08uacd3cuto7v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.petmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALXhj2m2AyN2nhVQ0Cfm0e6dDp_QXFksw',
    appId: '1:196219608404:web:74b5964960ae3b9d28bcc1',
    messagingSenderId: '196219608404',
    projectId: 'petmatch-77d5b',
    authDomain: 'petmatch-77d5b.firebaseapp.com',
    storageBucket: 'petmatch-77d5b.firebasestorage.app',
    measurementId: 'G-3256GKDNZ7',
  );
}
